### ISSUE TITLE
ramp packer

### ISSUE THREAD

**Issue by drumcircle** [RedBeardLab/rediSQL#113]
To load this extension in Redis Enterprise I need to pack it first.  Do you have a packed version of PRO?

https://github.com/RedisLabs/RAMP

Getting these errors on my system

Command:

XXXXXX:bin xxx$ ramp pack ~/xxx/RedisSQL/redisql_v1.0.2_PRO_x86_64.so -a "Anthony" -e "me@somewhere.com" -A "x86_64" -d "RedisSQL" -h "https://redisql.redbeardlab.com/" -l "Commercial" -r "1.1.2"

Error stream:

Traceback (most recent call last):
  File "/Users/xxx/anaconda/bin/ramp", line 11, in <module>
    sys.exit(ramp())
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/RAMP/ramp.py", line 106, in pack
    return package(module, **kwargs)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/RAMP/packer.py", line 96, in package
    module = discover_modules_commands(module_path, metadata["command_line_args"])
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/RAMP/commands_discovery.py", line 117, in discover_modules_commands
    module = _load_module(redis_client, path_to_module, module_args)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/RAMP/commands_discovery.py", line 61, in _load_module
    os.path.abspath(path_to_module), module_args))
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Error loading the extension. Please check the server logs.

**Comment by siscia** [comment]
Sorry, I am not that up to date with RedisLab and RAMP.

I will see what can be done tomorrow Europe time zone!

Anyhow, can you share what are the server logs?

```
 redis.exceptions.ResponseError: Error loading the extension. Please check the server logs.
 ```

**Comment by siscia** [comment]
The creation of the module.zip worked out of the box for me.

I am using python2 and I put `redis-server` in my PATH.

However, I cannot really test what I created.

I will create the manifest file so that it will be simpler to run RAMP.
